# creates new .txt file in folder (called YM.txt) containing matrix of 
# YM values from each .txt file generated by indenter

import numpy as np
import os


# directory = os.getcwd()
directory = '/Users/lauraforster/Documents/Uni/3 - PhD/Nanoindentation/NI_Data/Data/Bleomycin/2w/48P/48P_1'
os.chdir(directory)

text = "E[eff] (Pa)"

YM = []

for filename in os.listdir(directory):
    if filename.endswith(".txt"):
        file = open(filename)
        lines = file.readlines()
        for line in lines:
            if text in line:
                YM.append(float(line[12:]))

lengthYM = len(YM)
YMAvSUM = 0
for x in range(lengthYM):
    YMAvSUM+= YM[x]
YMAv = YMAvSUM/lengthYM

directory = '/Users/lauraforster/Documents/Uni/3 - PhD/Nanoindentation/NI_Data/Data/Bleomycin/2w/48P'
os.chdir(directory)

with open('YM.txt', 'w') as f:
    for x in range(lengthYM):
        f.write(str(YM[x]))
        f.write('\n')
with open('YM.txt', 'a') as f:
    f.write('\n')
    f.write('\n')
    f.write('Average YM = ')
    f.write(str(YMAv))